apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: codegen
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: codegen
    spec:
      containers:
      - name: codegen
        image: cicenter.azurecr.io/codegencore:$(Build.BuildNumber)
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Production"
        imagePullPolicy: Always
        ports:
        - containerPort: 5001
      imagePullSecrets:
      - name: acr-auth
---
apiVersion: v1
kind: Service
metadata:
  name: codegen-svc
spec:
  type: LoadBalancer
  ports:
  - port: 52677
  selector:
    app: codegen