apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: codegen
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: codegen
    spec:
      containers:
      - name: codegen-app
        image: cicenter.azurecr.io/codegencore:$(Build.BuildNumber)
        imagePullPolicy: Always
        ports:
        - containerPort: 52677
      imagePullSecrets:
      - name: acr-auth

apiVersion: v1
kind: Service
metadata:
  name: codegen
spec:
  type: LoadBalancer
  ports:
  - port: 8080
  selector:
    app: codegen